---
- hosts: cig
  become: yes
  roles:
    - prometheus
  tasks:

    - name: install grafana
      apt: deb={{ grafana_release_url }}/{{ grafana_deb }}

    - name: enable and restart some services
      systemd:
        daemon_reload=yes
        enabled=yes
        state=restarted
        name={{ item }}
      with_items:
        - grafana-server
