---
- hosts: cig
  become: yes
  tasks:
    - name: add influxdata repo key
      apt_key: data={{ influxdata_repo_key }}

    - name: add influxdata repo
      apt_repository: repo={{ item }}
      with_items:
        - "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

    - name: install packages
      apt:
        name={{ item }}
        update_cache=yes
        cache_valid_time=1800
        state=latest
      with_items:
        - collectd
        - influxdb

    - name: install grafana
      apt: deb={{ grafana_release_url }}/{{ grafana_deb }}

    - name: configure collectd
      copy:
        dest: /etc/collectd/collectd.conf
        src: etc/collectd/collectd.conf

    - name: configure influxdb
      copy:
        dest: /etc/influxdb/influxdb.conf
        src: etc/influxdb/influxdb.conf

    - name: enable and restart some services
      systemd:
        daemon_reload=yes
        enabled=yes
        state=restarted
        name={{ item }}
      with_items:
        - collectd
        - influxdb
        - grafana-server
